- name: Configuring Healthcare demo
  hosts: localhost
  connection: local
  tasks:
    - name: "Configure createModule.cli"
      replace:
        path: '{{ cli_dir }}/createModule.cli'
        regexp: '--resources=.*\.jar'
        replace: '--resources={{ binaries_dir }}/postgresql-9.4.1212.jar'
        backup: yes 
    - name: "Configure deployVDB.cli"
      replace:
        path: '{{ cli_dir }}/deployVDB.cli'
        regexp: 'deploy .*\/(\w+-vdb\.xml)'
        replace: 'deploy {{ vdb_dir }}/\1'
        backup: yes
    - name: "Create JDV Modules"
      shell: 'bash -c "{{ jboss_home }}/bin/jboss-cli.sh --connect --controller=localhost:{{ jboss_eap_instance_cli_default_port }} --file={{ cli_dir }}/createModule.cli "'
      ignore_errors: yes
    - name: "Create JDV Drivers"
      shell: 'bash -c "{{ jboss_home }}/bin/jboss-cli.sh --connect --controller=localhost:{{ jboss_eap_instance_cli_default_port }} --file={{ cli_dir }}/createDriver.cli "'
      ignore_errors: yes
    - name: "Create JDV Datasources"
      shell: 'bash -c "{{ jboss_home }}/bin/jboss-cli.sh --connect --controller=localhost:{{ jboss_eap_instance_cli_default_port }} --file={{ cli_dir }}/{{ item | basename }}"'
      with_items: "{{ jdv_cli_datasource_list }}"
      ignore_errors: yes
    - name: "Reload Configuration"
      shell: 'bash -c "{{ jboss_home }}/bin/jboss-cli.sh --connect --controller=localhost:{{ jboss_eap_instance_cli_default_port }} --command=:reload"'
      ignore_errors: no
    - name: "Waiting 10 seconds for reloading"
      pause:
        seconds: 10
    - name: "Deploy VDBs"
      shell: 'bash -c "{{ jboss_home }}/bin/jboss-cli.sh --connect --controller=localhost:{{ jboss_eap_instance_cli_default_port }} --file={{ cli_dir }}/deployVDB.cli "'
      ignore_errors: no
    - name: "Populate JDG"
      shell: 'bash -c "cd {{ jdg_cache_producer_dir }} &&  mvn clean package exec:java -Djdg.hostname=localhost -Djdg.port=11322 -Dpostgresql.hostname=localhost -Dpostgresql.port=5432 -Dpostgresql.dbname=medical -Dpostgresql.username=postgres -Dpostgresql.password=postgres -Djdg.cache.name.bloodpressurelevel=bloodPressureLevelCache -Djdg.cache.name.glucoselevel=glucoseLevelCache -Djdg.cache.name.bpglevel=bpgLevelCache"'
      ignore_errors: no
    - name: "Initialize JDV Materialization"
      shell: 'bash -c "{{ jboss_home }}/bin/jboss-cli.sh --connect --controller=localhost:{{ jboss_eap_instance_cli_default_port }} --file={{ cli_dir }}/initializeMaterialization.cli"'
      ignore_errors: no