- name: Healthcare demo
  hosts: localhost
  connection: local
  tasks: 
    - name: "Start JDG 7.1.1 Server with port-offset {{ jdg_instance_port_offset }}"
      shell: 'bash -c "nohup {{ jdg_home }}/bin/standalone.sh -c {{ jdg_instance_standalone_file }} -Djboss.socket.binding.port-offset={{ jdg_instance_port_offset }} -Djboss.management.native.port={{ jdg_instance_cli_port }} -Djboss.server.base.dir={{ jdg_instance_dir }} &"'
      ignore_errors: no
    - name: "Start JDV 6.4 Server with port-offset {{ jboss_eap_instance_port_offset }}"
      shell: 'bash -c "nohup {{ jboss_home }}/bin/standalone.sh -c {{ jboss_eap_instance_standalone_file }} -Djboss.socket.binding.port-offset={{ jboss_eap_instance_port_offset }} -Djboss.management.native.port={{ jboss_eap_instance_cli_default_port }} -Djboss.server.base.dir={{ jboss_eap_instance_dir }} &"'
      ignore_errors: no
        
   